% note: x0 integral goes from -L2/2 to L2/2, but it should be -L1/2 to L1/2
function [C1_s_int, C3_s_int] = C_1_3_integrations(B0, tau, z0, ytop, ybot, xi, k, L1, L2, w2, aTol, rTol)

psi = @(x, y, z, x0, z0) (z-z0)./sqrt((x-x0).^2 + y.^2 + (z-z0));

By_integrand = @(x, y, z, x0) B0*y/(2*pi).*(psi(x, y, z, x0, z0) - ...
    psi(x, y, z, x0, -z0)).*exp(1i.*x0.*pi/tau)./((x-x0).^2 + y.^2);
            

C1_s_integrand = @(x0,x,z) By_integrand(x,ytop,z,x0).*exp(-1i.*(xi*x + ...
    k*z));
C1_s_int = integral3(@(x0,x,z)C1_s_integrand(x0,x,z),-L1/2, ...
    L1/2, -L2/2, L2/2, -w2/2, w2/2,'Method','iterated',...
                               'AbsTol',aTol,'RelTol',rTol);
% region 3: y = d2
C3_s_integrand = @(x0,x,z) By_integrand(x,ybot,z,x0).*exp(-1i.*(xi*x +...
    k*z));
C3_s_int = integral3(@(x0,x,z)C3_s_integrand(x0,x,z),-L1/2, L1/2,...
    -L2/2, L2/2, -w2/2, w2/2,'Method','iterated',...
                               'AbsTol',aTol,'RelTol',rTol);
end